#pragma config(Sensor, dgtl1,  frbutton,       sensorTouch)
#pragma config(Sensor, dgtl12, rebutton,       sensorTouch)
#pragma config(Motor,  port2,           leftrearrmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           frontLM,       tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           frontRM,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           rightrearmotor, tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		//this code is repeated multiple times in order to drive the vehicle foward and to turn the vehicle randomly*/
		motor(frontLM) = 63;
		motor(rightrearmotor) = 63;
		motor(leftrearrmotor) = 63;
		motor(frontRM) = 63;
		wait1Msec(2500);
		motor(frontLM) = 63;
		motor(rightrearmotor) = 63;
		motor(leftrearrmotor) = 63;
		wait1Msec(1000);
		// this if statement reverses then turns vehicle to the right*/
		if(SensorValue(frbutton) == 1)
		{
			motor(frontLM) = 63;
			motor(rightrearmotor) = 63;
			motor(leftrearrmotor) = 63;
			motor(frontRM) = 63;
			wait1Msec(1000);
			motor(frontLM) = 63;
			motor(rightrearmotor) = 63;
			motor(leftrearrmotor) = 63;
			wait1Msec(1000);
		}
		motor(frontLM) = 63;
		motor(rightrearmotor) = 63;
		motor(leftrearrmotor) = 63;
		motor(frontRM) = 63;
		wait1Msec(2500);
		motor(frontRM) = 63;
		motor(rightrearmotor) = 63;
		motor(leftrearrmotor) = 63;
		wait1Msec(1000);
		// this if statement reverses then turns vehicle to the right*/
		if(SensorValue(rebutton) == 1)
		{
			motor(frontLM) = 63;
			motor(rightrearmotor) = 63;
			motor(leftrearrmotor) = 63;
			motor(frontRM) = 63;
			wait1Msec(1000);
			motor(frontLM) = 63;
			motor(rightrearmotor) = 63;
			motor(leftrearrmotor) = 63;
			wait1Msec(1000);
		}
		motor(frontLM) = 63;
		motor(rightrearmotor) = 63;
		motor(leftrearrmotor) = 63;
		motor(frontRM) = 63;
		wait1Msec(2500);
		motor(frontLM) = 63;
		motor(rightrearmotor) = 63;
		motor(leftrearrmotor) = 63;
		wait1Msec(1000);






	}


}
