#pragma config(Sensor, dgtl1,  e_StopBtn,      sensorTouch)
#pragma config(Sensor, dgtl2,  Button,         sensorTouch)
#pragma config(Motor,  port1,           motor,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

*/

bool emerg = false;
bool load = false;

task e_stop()
{
	while (true)
	{
		if(SensorValue(e_StopBtn) == 1)
		{
			stopAllTasks();
			emerg == true;
			break();
		}
	}

}

task main()
{
	startTask(e_stop);
	if emerg == true
	{
		break();
	}
	while (true)
	{
		if(SensorValue(Button) == 1)
		{
			if load = false
			{
				start Motor;
				wait();
				stop Motor;
			}
			if load = true
			{
				start Motor;
				wait();
				stop Motor;
			}
		}
	}
}
