#pragma config(Sensor, in1,    linefollowerMid, sensorLineFollower)
#pragma config(Sensor, in2,    linefollowerRight, sensorLineFollower)
#pragma config(Sensor, in3,    linefollowerLeft, sensorLineFollower)
#pragma config(Motor,  port2,           leftrearMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           frontleftMotor, tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           frontrightMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           rightrearMotor, tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Tumbler #4
Team Members: David, Hunter, Ethan, John
Date:10/31/2019
Section: Block B


Task Description:

To get the Tumbler to read and follow the line

Pseudocode:
Robot reads the line.
Robot follows the line.
Robot stops right before hitting the wall.

*/

task main()
//Program begins, insert code within curly braces
{
	bool hitwall = false;
	while(true)
	{
		if(hitwall == true)
		{
			break;
		}
		if(SensorValue(in1) >= 2550)
		{
			startMotor(rightrearMotor, -63);
			startMotor(frontleftMotor, 63);
			startMotor(frontrightMotor, 63);
			startMotor(leftrearMotor,  -63);
			waitUntil(SensorValue(in1) <= 2550 || SensorValue(dgtl1) == 5);
			stopMotor(frontleftMotor);
			stopMotor(frontrightMotor);
			stopMotor(rightrearMotor);
			stopMotor(leftrearMotor);
		}
		if(SensorValue(in3) >= 2550)

		{
			startMotor(frontleftMotor, -35);
			startMotor(frontrightMotor, 35);
			startMotor(leftrearMotor, 35);
			startMotor(rightrearMotor, -35);
			waitUntil(SensorValue(in1) >= 2550);
		}

		if(SensorValue(in2) >= 2550)
		{
			startMotor(frontleftMotor, 30);
			startMotor(frontrightMotor, -30);
			startMotor(leftrearMotor, -30);
			startMotor(rightrearMotor, -30);
			waitUntil(SensorValue(in1) >=2550);


		}

	}
}
