#pragma config(Sensor, dgtl1,  bumper1,        sensorTouch)
#pragma config(Sensor, dgtl12, bumper2,        sensorTouch)
#pragma config(Motor,  port2,           backleft,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           frontleft,     tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           frontright,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           backright,     tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Double Bumper
  Team Members:David, Hunter, Ethan, and John
  Date:10/22/2019
  Section: Block B


  Task Description:
	To hit a wall, reverse, rotate and and then move forawrd

  Pseudocode:
	To hit a wall
	After hitting the wall it backs up 1 rev
	Then after backing up it rotates 90 degrees
	Finally after rotating it moves forward

*/

task main()
{                                     //Program begins, insert code within curly braces
wait(2);
while(1 == 1){
	startMotor(backleft,-47);
	startMotor(frontleft, 45);
	startMotor(backright,-45);
	startMotor(frontright, 45);
	waitUntil(SensorValue(bumper1) ==1 || SensorValue(bumper2) ==1);
	{
		stopMotor(backleft);
		stopMotor(frontleft);
		stopMotor(frontright);
		stopMotor(backright);
		wait(0.2);
		startMotor(backleft,47);
		startMotor(frontleft, -45);
		startMotor(backright,45);
		startMotor(frontright, -45);
		wait(random(1));
		stopMotor(backleft);
		stopMotor(frontleft);
		stopMotor(frontright);
		stopMotor(backright);
		wait(0.2);
		startMotor(backleft,65);
		startMotor(frontleft,-63);
		startMotor(backright,-63);
		startMotor(frontright, 63);
		wait(random(3));
		stopMotor(backleft);
		stopMotor(frontleft);
		stopMotor(backright);
		stopMotor(frontright);
	}
	}
}
