#pragma config(Motor,  port2,           backleftmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           frontleftmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           frontrightmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           backrightmotor, tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Tumbler #2
  Team Members:David, Ethan, John, Hunter
  Date: 10/17/2018
  Section: Block B


  Task Description:
	Get the robot to navigate a short maze

  Pseudocode:
	Move forward, stop, then rotate 90 degrees.
	Forward a short distance,stop, then rotate 90.
	Move forward, stop, then rotate 180 degrees the opposite way.
	Forward a short distance then turn 90 degrees in the same direction.
	Move forward then stop at the finish space.


*/

task main()
                                     //Program begins, insert code within curly braces
{
wait(1);
startMotor(backleftmotor,-63);
startMotor(frontleftmotor,63);
startMotor(backrightmotor,-63);
startMotor(frontrightmotor, 63);
wait(1.4);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,-63);
startMotor(frontleftmotor,63);
startMotor(backrightmotor,63);
startMotor(frontrightmotor, -63);
wait(0.67);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,-63);
startMotor(frontleftmotor,63);
startMotor(backrightmotor,-63);
startMotor(frontrightmotor, 63);
wait(0.635);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,-63);
startMotor(frontleftmotor,63);
startMotor(backrightmotor,63);
startMotor(frontrightmotor, -63);
wait(1.3);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,63);
startMotor(frontleftmotor,-63);
startMotor(backrightmotor,-63);
startMotor(frontrightmotor,63);
wait(0.74);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,-63);
startMotor(frontleftmotor,63);
startMotor(backrightmotor,-63);
startMotor(frontrightmotor, 63);
wait(0.635);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,63);
startMotor(frontleftmotor,-63);
startMotor(backrightmotor,-63);
startMotor(frontrightmotor,63);
wait(0.79);
stopMotor(backleftmotor);
stopMotor(frontleftmotor);
stopMotor(backrightmotor);
stopMotor(frontrightmotor);
wait(0.2);
startMotor(backleftmotor,-63);
startMotor(frontleftmotor,63);
startMotor(backrightmotor,-63);
startMotor(frontrightmotor, 63);
wait(1.375);
}
