#pragma config(Sensor, dgtl1,  bumpswitch,     sensorTouch)
#pragma config(Motor,  port2,           backleftmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           frontleftmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           frontrightmotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           backrightmotor, tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Tumbler Chalenge #3
  Team Members:David, Hunter, Ethan, and John
  Date: 10/19/2018
  Section: Block B


  Task Description:
	To hit a wall, reverse, rotate and and then move forawrd

  Pseudocode:
	To hit a wall
	After hitting the wall it backs up 1 rev
	Then after backing up it rotates 90 degrees
	Finally after rotating it moves forward

*/

task main()
{						//Program begins, insert code within curly braces
	while(1 == 1)
	{
	startMotor(backleftmotor,-37);
	startMotor(frontleftmotor, 35);
	startMotor(backrightmotor,-35);
	startMotor(frontrightmotor, 35);
	waitUntil(SensorValue(bumpswitch) ==1);
	{
		stopMotor(backleftmotor);
		stopMotor(frontleftmotor);
		stopMotor(frontrightmotor);
		stopMotor(backrightmotor);
		wait(0.2);
		startMotor(backleftmotor,35);
		startMotor(frontleftmotor, -35);
		startMotor(backrightmotor,35);
		startMotor(frontrightmotor, -35);
		wait(random(3));
		stopMotor(backleftmotor);
		stopMotor(frontleftmotor);
		stopMotor(frontrightmotor);
		stopMotor(backrightmotor);
		wait(0.2);
		startMotor(backleftmotor,-63);
		startMotor(frontleftmotor,-63);
		startMotor(backrightmotor,63);
		startMotor(frontrightmotor, 63);
		wait(0.87);
		stopMotor(backleftmotor);
		stopMotor(frontleftmotor);
		stopMotor(backrightmotor);
		stopMotor(frontrightmotor);
	}
	}
}
