#pragma config(Motor,  port2,           backleftM,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontleftM,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           frontrightM,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backrightM,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait(2);
	startMotor(frontrightM, 63);
	startMotor(backrightM, -63);
	startMotor(backleftM, 63);
	startMotor(frontleftM, -63);
	wait(0.75);
	stopMotor(frontrightM);
	stopMotor(backrightM);
	stopMotor(frontleftM);
	stopMotor(backleftM);
	wait(2);
	startMotor(frontrightM, -63);
	startMotor(backrightM, 63);
	startMotor(backleftM, -63);
	startMotor(frontleftM, 63);
	wait(0.75);
}
