#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1)
	{
		startMotor(backRight, -37);
		startMotor(frontLeft, 35);
		startMotor(frontRight, 37);
		startMotor(backLeft, -35);
		waitUntil(SensorValue(bumpSwitch) == 1);
		{
			stopMotor(backRight);
			stopMotor(frontLeft);
			stopMotor(frontRight);
			stopMotor(backLeft);
			wait(0.2);
			startMotor(backRight, 35);
			startMotor(frontLeft, -35);
			startMotor(frontRight, -35);
			startMotor(backLeft, 35);
			wait(random(3));
			stopMotor(backRight);
			stopMotor(frontLeft);
			stopMotor(frontRight);
			stopMotor(backLeft);
			wait(0.2);
			startMotor(backRight, 63);
			startMotor(frontLeft, -63);
			startMotor(frontRight, 63);
			startMotor(backLeft, -63);
			wait(random(5));
			stopMotor(backRight);
			stopMotor(frontLeft);
			stopMotor(frontRight);
			stopMotor(backLeft);
		}
	}
}
